# Generated by Django 4.0 on 2022-01-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaski', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
    ]
