# Generated by Django 4.0 on 2022-01-11 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaski', '0006_usuario_usuario_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_activo',
            new_name='login',
        ),
    ]
